### PR TITLE
Changed Some Stuff

### PR DESCRIPTION
**Pull request by ghost**
- added eval command
- added fact command
- changed "{message.author.name}#{message.author.discriminator}" to "{message.author}" (because its basically the same)

### CODE REVIEW

**Comment by niztg** [comment]
????

**Comment by DJJ05** [comment]
I agree lmfao ^

**Comment by DJJ05** [comment]
ill think about this later @KILR007 , not my first priority rn lol

**Comment by ghost** [comment]
kk

**Comment by DJJ05** [comment]
I promise I'll look at this tomorrow lol, been busy af, if I don't respond in 24h then I'm either dead or high

**Comment by ghost** [comment]
haha fair
you merged

**Comment by DJJ05** [comment]
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.fun' raised an error: AttributeError: 'Command' object has no attribute 'casefold' @KILR007

**Pull request merged**
