### PR TITLE
Made utopia cog better

### PR DESCRIPTION
**Pull request by niztg**
Notes:
- Fixed horrible `∫√∆` thing.
- Made `created` an actual datetime object
- Made the code and imports cleaner

this isn't tested btw

~ with <3 from niz

### CODE REVIEW

**Comment by DJJ05** [comment]
argh, I love this but there are hundreds of nominations already saved and Idk how I would convert those into the cool dict format you've added :(

**Review by DJJ05 — COMMENTED** [review]
Need to figure out how I'd convert over the current nominations that are saved in the old format

**Comment by niztg** [comment]
right

**Comment by niztg** [comment]
good luck lmao

**Comment by DJJ05** [comment]
lmao I'll try to find a way

**Pull request closed without merging**
